language: node_js
node_js:
  - lts/*
script: npm run test:coverage
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
deploy:
  edge: true
  provider: npm
  on:
    branch: master
    tags: true
